import { hotelCards } from '../query/mock'
import { HOTEL_LIST_POOL } from '../list/mock'

export interface HotelRoomPlan {
  id: string
  name: string
  coverImage: string
  area: string
  bedType: string
  guestText: string
  breakfast: '含早餐' | '不含早餐'
  cancellable: boolean
  tags: string[]
  originalPrice: number
  price: number
  stock: number
}

export interface HotelDetailData {
  id: string
  name: string
  star: string
  address: string
  rating: number
  reviewCount: number
  collectCount: number
  facilities: string[]
  mapLabel: string
  gallery: {
    id: string
    title: string
    imageUrl: string
  }[]
  roomPlans: HotelRoomPlan[]
}

const DETAIL_RECORDS: Record<
  string,
  Omit<HotelDetailData, 'id' | 'name' | 'star' | 'address'>
> = {
  'h-001': {
    rating: 4.8,
    reviewCount: 12681,
    collectCount: 9034,
    facilities: ['免费 Wi-Fi', '自助早餐', '健身房', '洗衣房', '会议室', '停车场'],
    mapLabel: '会展中心 / 福田口岸',
    gallery: [
      {
        id: 'g-001',
        title: '封面',
        imageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'g-002',
        title: '精选',
        imageUrl: 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'g-003',
        title: '相册',
        imageUrl: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1600&q=80',
      },
    ],
    roomPlans: [
      {
        id: 'h-001-rp-1',
        name: '行政套房',
        coverImage: 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=800&q=80',
        area: '58㎡',
        bedType: '1张特大床',
        guestText: '2人',
        breakfast: '含早餐',
        cancellable: true,
        tags: ['免费取消', '含早餐', '高层景观'],
        originalPrice: 1388,
        price: 928,
        stock: 3,
      },
      {
        id: 'h-001-rp-2',
        name: '商务大床房',
        coverImage: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80',
        area: '32㎡',
        bedType: '1张大床',
        guestText: '2人',
        breakfast: '含早餐',
        cancellable: false,
        tags: ['近电梯', '含早餐'],
        originalPrice: 699,
        price: 468,
        stock: 8,
      },
      {
        id: 'h-001-rp-3',
        name: '高级双床房',
        coverImage: 'https://images.unsplash.com/photo-1631049552240-59c37f38802b?auto=format&fit=crop&w=800&q=80',
        area: '35㎡',
        bedType: '2张单人床',
        guestText: '2人',
        breakfast: '不含早餐',
        cancellable: true,
        tags: ['可加床', '免费取消'],
        originalPrice: 738,
        price: 528,
        stock: 4,
      },
      {
        id: 'h-001-rp-4',
        name: '特惠大床房',
        coverImage: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=800&q=80',
        area: '28㎡',
        bedType: '1张大床',
        guestText: '2人',
        breakfast: '不含早餐',
        cancellable: false,
        tags: ['限时特惠'],
        originalPrice: 598,
        price: 398,
        stock: 0,
      },
    ],
  },
  'h-002': {
    rating: 4.7,
    reviewCount: 8943,
    collectCount: 6211,
    facilities: ['海景阳台', '儿童乐园', '无边泳池', '健身房', '停车场', '接机服务'],
    mapLabel: '三亚湾 / 海月广场',
    gallery: [
      {
        id: 'g-101',
        title: '封面',
        imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'g-102',
        title: '精选',
        imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'g-103',
        title: '相册',
        imageUrl: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1600&q=80',
      },
    ],
    roomPlans: [
      {
        id: 'h-002-rp-1',
        name: '海景家庭套房',
        coverImage: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80',
        area: '72㎡',
        bedType: '1张特大床+1张沙发床',
        guestText: '3人',
        breakfast: '含早餐',
        cancellable: true,
        tags: ['海景露台', '免费取消', '含早餐'],
        originalPrice: 1688,
        price: 1088,
        stock: 2,
      },
      {
        id: 'h-002-rp-2',
        name: '海景豪华双床房',
        coverImage: 'https://images.unsplash.com/photo-1563911302283-d2bc129e7570?auto=format&fit=crop&w=800&q=80',
        area: '42㎡',
        bedType: '2张双人床',
        guestText: '2人',
        breakfast: '含早餐',
        cancellable: true,
        tags: ['高楼层', '免费取消'],
        originalPrice: 1188,
        price: 828,
        stock: 6,
      },
      {
        id: 'h-002-rp-3',
        name: '园景大床房',
        coverImage: 'https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=800&q=80',
        area: '32㎡',
        bedType: '1张大床',
        guestText: '2人',
        breakfast: '不含早餐',
        cancellable: false,
        tags: ['性价比'],
        originalPrice: 888,
        price: 688,
        stock: 9,
      },
      {
        id: 'h-002-rp-4',
        name: '观海阳台房',
        coverImage: 'https://images.unsplash.com/photo-1566669437685-0248e70422c9?auto=format&fit=crop&w=800&q=80',
        area: '38㎡',
        bedType: '1张大床',
        guestText: '2人',
        breakfast: '含早餐',
        cancellable: true,
        tags: ['阳台海景', '免费取消'],
        originalPrice: 1088,
        price: 788,
        stock: 1,
      },
    ],
  },
  'h-003': {
    rating: 4.6,
    reviewCount: 6328,
    collectCount: 3806,
    facilities: ['自助洗衣房', '24小时前台', '商务打印', '行李寄存', '免费 Wi-Fi', '机器人送物'],
    mapLabel: '西湖商圈 / 龙翔桥',
    gallery: [
      {
        id: 'g-201',
        title: '封面',
        imageUrl: 'https://images.unsplash.com/photo-1501117716987-c8e1ecb2101d?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'g-202',
        title: '精选',
        imageUrl: 'https://images.unsplash.com/photo-1455587734955-081b22074882?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'g-203',
        title: '相册',
        imageUrl: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1600&q=80',
      },
    ],
    roomPlans: [
      {
        id: 'h-003-rp-1',
        name: '高级大床房',
        coverImage: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80',
        area: '30㎡',
        bedType: '1张大床',
        guestText: '2人',
        breakfast: '不含早餐',
        cancellable: false,
        tags: ['商旅推荐'],
        originalPrice: 568,
        price: 388,
        stock: 6,
      },
      {
        id: 'h-003-rp-2',
        name: '精选双床房',
        coverImage: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=800&q=80',
        area: '34㎡',
        bedType: '2张单人床',
        guestText: '2人',
        breakfast: '含早餐',
        cancellable: true,
        tags: ['免费取消', '含早餐'],
        originalPrice: 648,
        price: 418,
        stock: 4,
      },
      {
        id: 'h-003-rp-3',
        name: '轻奢套房',
        coverImage: 'https://images.unsplash.com/photo-1590490359683-658d3d23f972?auto=format&fit=crop&w=800&q=80',
        area: '48㎡',
        bedType: '1张特大床',
        guestText: '2人',
        breakfast: '含早餐',
        cancellable: true,
        tags: ['浴缸', '免费取消'],
        originalPrice: 798,
        price: 588,
        stock: 2,
      },
      {
        id: 'h-003-rp-4',
        name: '特惠房',
        coverImage: 'https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=800&q=80',
        area: '24㎡',
        bedType: '1张双人床',
        guestText: '2人',
        breakfast: '不含早餐',
        cancellable: false,
        tags: ['限时特惠'],
        originalPrice: 498,
        price: 328,
        stock: 0,
      },
    ],
  },
  'h-004': {
    rating: 4.7,
    reviewCount: 7021,
    collectCount: 4512,
    facilities: ['行政酒廊', '24小时前台', '商务会议室', '健身房', '免费 Wi-Fi', '停车场'],
    mapLabel: '国贸商圈 / CBD',
    gallery: [
      {
        id: 'g-301',
        title: '封面',
        imageUrl: 'https://images.unsplash.com/photo-1519821172141-b5d8a6f3f8e2?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'g-302',
        title: '精选',
        imageUrl: 'https://images.unsplash.com/photo-1616047006789-b7d5b0b95d16?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'g-303',
        title: '相册',
        imageUrl: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1600&q=80',
      },
    ],
    roomPlans: [
      {
        id: 'h-004-rp-1',
        name: '行政大床房',
        coverImage: 'https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=800&q=80',
        area: '38㎡',
        bedType: '1张特大床',
        guestText: '2人',
        breakfast: '含早餐',
        cancellable: true,
        tags: ['行政礼遇', '免费取消', '含早餐'],
        originalPrice: 1198,
        price: 798,
        stock: 5,
      },
      {
        id: 'h-004-rp-2',
        name: '商务双床房',
        coverImage: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=800&q=80',
        area: '36㎡',
        bedType: '2张单人床',
        guestText: '2人',
        breakfast: '含早餐',
        cancellable: false,
        tags: ['高层安静', '含早餐'],
        originalPrice: 1038,
        price: 688,
        stock: 8,
      },
      {
        id: 'h-004-rp-3',
        name: '轻享大床房',
        coverImage: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80',
        area: '28㎡',
        bedType: '1张大床',
        guestText: '2人',
        breakfast: '不含早餐',
        cancellable: true,
        tags: ['免费取消', '性价比'],
        originalPrice: 868,
        price: 598,
        stock: 6,
      },
      {
        id: 'h-004-rp-4',
        name: '限时特惠房',
        coverImage: 'https://images.unsplash.com/photo-1616486029423-aaa4789e8c9a?auto=format&fit=crop&w=800&q=80',
        area: '24㎡',
        bedType: '1张双人床',
        guestText: '2人',
        breakfast: '不含早餐',
        cancellable: false,
        tags: ['限时特惠'],
        originalPrice: 758,
        price: 538,
        stock: 2,
      },
    ],
  },
  'h-005': {
    rating: 4.8,
    reviewCount: 9412,
    collectCount: 6724,
    facilities: ['海景露台', '无边泳池', '自助早餐', '儿童乐园', '停车场', '接机服务'],
    mapLabel: '环岛路 / 曾厝垵',
    gallery: [
      {
        id: 'g-401',
        title: '封面',
        imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'g-402',
        title: '精选',
        imageUrl: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'g-403',
        title: '相册',
        imageUrl: 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&w=1600&q=80',
      },
    ],
    roomPlans: [
      {
        id: 'h-005-rp-1',
        name: '海景阳台套房',
        coverImage: 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=800&q=80',
        area: '62㎡',
        bedType: '1张特大床',
        guestText: '2人',
        breakfast: '含早餐',
        cancellable: true,
        tags: ['海景露台', '免费取消', '含早餐'],
        originalPrice: 1788,
        price: 1198,
        stock: 3,
      },
      {
        id: 'h-005-rp-2',
        name: '海景双床房',
        coverImage: 'https://images.unsplash.com/photo-1563911302283-d2bc129e7570?auto=format&fit=crop&w=800&q=80',
        area: '42㎡',
        bedType: '2张双人床',
        guestText: '2人',
        breakfast: '含早餐',
        cancellable: true,
        tags: ['家庭友好', '免费取消'],
        originalPrice: 1388,
        price: 928,
        stock: 7,
      },
      {
        id: 'h-005-rp-3',
        name: '园景大床房',
        coverImage: 'https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=800&q=80',
        area: '30㎡',
        bedType: '1张大床',
        guestText: '2人',
        breakfast: '不含早餐',
        cancellable: false,
        tags: ['性价比'],
        originalPrice: 1098,
        price: 768,
        stock: 8,
      },
      {
        id: 'h-005-rp-4',
        name: '特惠房',
        coverImage: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80',
        area: '26㎡',
        bedType: '1张双人床',
        guestText: '2人',
        breakfast: '不含早餐',
        cancellable: false,
        tags: ['限量'],
        originalPrice: 978,
        price: 698,
        stock: 1,
      },
    ],
  },
  'h-006': {
    rating: 4.6,
    reviewCount: 5581,
    collectCount: 3348,
    facilities: ['亲子乐园', '洗衣房', '免费 Wi-Fi', '自助早餐', '行李寄存', '健身房'],
    mapLabel: '春熙路 / 太古里',
    gallery: [
      {
        id: 'g-501',
        title: '封面',
        imageUrl: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'g-502',
        title: '精选',
        imageUrl: 'https://images.unsplash.com/photo-1631049552240-59c37f38802b?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'g-503',
        title: '相册',
        imageUrl: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=1600&q=80',
      },
    ],
    roomPlans: [
      {
        id: 'h-006-rp-1',
        name: '亲子家庭房',
        coverImage: 'https://images.unsplash.com/photo-1631049552240-59c37f38802b?auto=format&fit=crop&w=800&q=80',
        area: '44㎡',
        bedType: '1张大床+1张单人床',
        guestText: '3人',
        breakfast: '含早餐',
        cancellable: true,
        tags: ['亲子用品', '免费取消', '含早餐'],
        originalPrice: 898,
        price: 628,
        stock: 4,
      },
      {
        id: 'h-006-rp-2',
        name: '精选双床房',
        coverImage: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=800&q=80',
        area: '32㎡',
        bedType: '2张单人床',
        guestText: '2人',
        breakfast: '不含早餐',
        cancellable: true,
        tags: ['免费取消'],
        originalPrice: 698,
        price: 488,
        stock: 9,
      },
      {
        id: 'h-006-rp-3',
        name: '商务大床房',
        coverImage: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80',
        area: '30㎡',
        bedType: '1张大床',
        guestText: '2人',
        breakfast: '含早餐',
        cancellable: false,
        tags: ['商旅推荐', '含早餐'],
        originalPrice: 748,
        price: 518,
        stock: 7,
      },
      {
        id: 'h-006-rp-4',
        name: '特惠房',
        coverImage: 'https://images.unsplash.com/photo-1590490359683-658d3d23f972?auto=format&fit=crop&w=800&q=80',
        area: '24㎡',
        bedType: '1张双人床',
        guestText: '2人',
        breakfast: '不含早餐',
        cancellable: false,
        tags: ['限时'],
        originalPrice: 598,
        price: 398,
        stock: 2,
      },
    ],
  },
  'h-007': {
    rating: 4.6,
    reviewCount: 5146,
    collectCount: 3094,
    facilities: ['古城接驳车', '免费 Wi-Fi', '自助早餐', '茶室', '洗衣房', '停车场'],
    mapLabel: '钟楼 / 回民街',
    gallery: [
      {
        id: 'g-601',
        title: '封面',
        imageUrl: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'g-602',
        title: '精选',
        imageUrl: 'https://images.unsplash.com/photo-1590490359683-658d3d23f972?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'g-603',
        title: '相册',
        imageUrl: 'https://images.unsplash.com/photo-1455587734955-081b22074882?auto=format&fit=crop&w=1600&q=80',
      },
    ],
    roomPlans: [
      {
        id: 'h-007-rp-1',
        name: '城景大床房',
        coverImage: 'https://images.unsplash.com/photo-1590490359683-658d3d23f972?auto=format&fit=crop&w=800&q=80',
        area: '31㎡',
        bedType: '1张大床',
        guestText: '2人',
        breakfast: '含早餐',
        cancellable: true,
        tags: ['古城景观', '免费取消', '含早餐'],
        originalPrice: 738,
        price: 498,
        stock: 7,
      },
      {
        id: 'h-007-rp-2',
        name: '雅致双床房',
        coverImage: 'https://images.unsplash.com/photo-1631049552240-59c37f38802b?auto=format&fit=crop&w=800&q=80',
        area: '33㎡',
        bedType: '2张单人床',
        guestText: '2人',
        breakfast: '不含早餐',
        cancellable: true,
        tags: ['免费取消'],
        originalPrice: 688,
        price: 468,
        stock: 6,
      },
      {
        id: 'h-007-rp-3',
        name: '家庭三人间',
        coverImage: 'https://images.unsplash.com/photo-1501117716987-c8e1ecb2101d?auto=format&fit=crop&w=800&q=80',
        area: '40㎡',
        bedType: '1张大床+1张单人床',
        guestText: '3人',
        breakfast: '含早餐',
        cancellable: false,
        tags: ['家庭优选', '含早餐'],
        originalPrice: 908,
        price: 628,
        stock: 3,
      },
      {
        id: 'h-007-rp-4',
        name: '特惠房',
        coverImage: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80',
        area: '22㎡',
        bedType: '1张双人床',
        guestText: '2人',
        breakfast: '不含早餐',
        cancellable: false,
        tags: ['限量'],
        originalPrice: 578,
        price: 398,
        stock: 1,
      },
    ],
  },
  'h-008': {
    rating: 4.7,
    reviewCount: 6632,
    collectCount: 4021,
    facilities: ['健身房', '自助早餐', '会议室', '洗衣房', '免费 Wi-Fi', '停车场'],
    mapLabel: '天河 / 珠江新城',
    gallery: [
      {
        id: 'g-701',
        title: '封面',
        imageUrl: 'https://images.unsplash.com/photo-1455587734955-081b22074882?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'g-702',
        title: '精选',
        imageUrl: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'g-703',
        title: '相册',
        imageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1600&q=80',
      },
    ],
    roomPlans: [
      {
        id: 'h-008-rp-1',
        name: '商务特大床房',
        coverImage: 'https://images.unsplash.com/photo-1455587734955-081b22074882?auto=format&fit=crop&w=800&q=80',
        area: '36㎡',
        bedType: '1张特大床',
        guestText: '2人',
        breakfast: '含早餐',
        cancellable: true,
        tags: ['免费取消', '含早餐', '高层景观'],
        originalPrice: 968,
        price: 668,
        stock: 6,
      },
      {
        id: 'h-008-rp-2',
        name: '精选双床房',
        coverImage: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=80',
        area: '34㎡',
        bedType: '2张单人床',
        guestText: '2人',
        breakfast: '不含早餐',
        cancellable: true,
        tags: ['免费取消'],
        originalPrice: 868,
        price: 598,
        stock: 8,
      },
      {
        id: 'h-008-rp-3',
        name: '轻享大床房',
        coverImage: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80',
        area: '28㎡',
        bedType: '1张大床',
        guestText: '2人',
        breakfast: '不含早餐',
        cancellable: false,
        tags: ['性价比'],
        originalPrice: 738,
        price: 528,
        stock: 5,
      },
      {
        id: 'h-008-rp-4',
        name: '限时特惠房',
        coverImage: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80',
        area: '24㎡',
        bedType: '1张双人床',
        guestText: '2人',
        breakfast: '不含早餐',
        cancellable: false,
        tags: ['限时'],
        originalPrice: 688,
        price: 488,
        stock: 0,
      },
    ],
  },
  'h-009': {
    rating: 4.6,
    reviewCount: 5874,
    collectCount: 3581,
    facilities: ['秦淮夜景露台', '自助早餐', '洗衣房', '行李寄存', '免费 Wi-Fi', '停车场'],
    mapLabel: '夫子庙 / 秦淮河',
    gallery: [
      {
        id: 'g-801',
        title: '封面',
        imageUrl: 'https://images.unsplash.com/photo-1501117716987-c8e1ecb2101d?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'g-802',
        title: '精选',
        imageUrl: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'g-803',
        title: '相册',
        imageUrl: 'https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=1600&q=80',
      },
    ],
    roomPlans: [
      {
        id: 'h-009-rp-1',
        name: '河景大床房',
        coverImage: 'https://images.unsplash.com/photo-1501117716987-c8e1ecb2101d?auto=format&fit=crop&w=800&q=80',
        area: '34㎡',
        bedType: '1张大床',
        guestText: '2人',
        breakfast: '含早餐',
        cancellable: true,
        tags: ['秦淮夜景', '免费取消', '含早餐'],
        originalPrice: 898,
        price: 618,
        stock: 5,
      },
      {
        id: 'h-009-rp-2',
        name: '雅致双床房',
        coverImage: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=800&q=80',
        area: '32㎡',
        bedType: '2张单人床',
        guestText: '2人',
        breakfast: '不含早餐',
        cancellable: true,
        tags: ['免费取消'],
        originalPrice: 818,
        price: 568,
        stock: 6,
      },
      {
        id: 'h-009-rp-3',
        name: '庭院家庭房',
        coverImage: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80',
        area: '42㎡',
        bedType: '1张大床+1张单人床',
        guestText: '3人',
        breakfast: '含早餐',
        cancellable: false,
        tags: ['家庭优选', '含早餐'],
        originalPrice: 998,
        price: 698,
        stock: 3,
      },
      {
        id: 'h-009-rp-4',
        name: '特惠房',
        coverImage: 'https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=800&q=80',
        area: '24㎡',
        bedType: '1张双人床',
        guestText: '2人',
        breakfast: '不含早餐',
        cancellable: false,
        tags: ['限时'],
        originalPrice: 688,
        price: 468,
        stock: 1,
      },
    ],
  },
  'h-010': {
    rating: 4.7,
    reviewCount: 6495,
    collectCount: 4178,
    facilities: ['观景露台', '亲子乐园', '自助早餐', '健身房', '免费 Wi-Fi', '停车场'],
    mapLabel: '滇池度假区 / 海埂',
    gallery: [
      {
        id: 'g-901',
        title: '封面',
        imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'g-902',
        title: '精选',
        imageUrl: 'https://images.unsplash.com/photo-1566669437685-0248e70422c9?auto=format&fit=crop&w=1600&q=80',
      },
      {
        id: 'g-903',
        title: '相册',
        imageUrl: 'https://images.unsplash.com/photo-1590490359683-658d3d23f972?auto=format&fit=crop&w=1600&q=80',
      },
    ],
    roomPlans: [
      {
        id: 'h-010-rp-1',
        name: '湖景家庭套房',
        coverImage: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80',
        area: '56㎡',
        bedType: '1张特大床+1张单人床',
        guestText: '3人',
        breakfast: '含早餐',
        cancellable: true,
        tags: ['湖景阳台', '免费取消', '含早餐'],
        originalPrice: 1388,
        price: 938,
        stock: 4,
      },
      {
        id: 'h-010-rp-2',
        name: '湖景大床房',
        coverImage: 'https://images.unsplash.com/photo-1566669437685-0248e70422c9?auto=format&fit=crop&w=800&q=80',
        area: '38㎡',
        bedType: '1张大床',
        guestText: '2人',
        breakfast: '含早餐',
        cancellable: true,
        tags: ['免费取消', '含早餐'],
        originalPrice: 1088,
        price: 758,
        stock: 6,
      },
      {
        id: 'h-010-rp-3',
        name: '园景双床房',
        coverImage: 'https://images.unsplash.com/photo-1590490359683-658d3d23f972?auto=format&fit=crop&w=800&q=80',
        area: '34㎡',
        bedType: '2张单人床',
        guestText: '2人',
        breakfast: '不含早餐',
        cancellable: false,
        tags: ['高性价比'],
        originalPrice: 928,
        price: 658,
        stock: 5,
      },
      {
        id: 'h-010-rp-4',
        name: '特惠房',
        coverImage: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80',
        area: '26㎡',
        bedType: '1张双人床',
        guestText: '2人',
        breakfast: '不含早餐',
        cancellable: false,
        tags: ['限时'],
        originalPrice: 798,
        price: 588,
        stock: 2,
      },
    ],
  },
}

const cloneRoomPlans = (roomPlans: HotelRoomPlan[]) => roomPlans.map((plan) => ({ ...plan, tags: [...plan.tags] }))

const uniqueStrings = (values: string[]) => Array.from(new Set(values.filter(Boolean)))

const getListVariant = (hotelId?: string, listItemId?: string) => {
  if (listItemId) {
    const matchedByListItemId = HOTEL_LIST_POOL.find((item) => item.itemId === listItemId)
    if (matchedByListItemId) {
      return matchedByListItemId
    }
  }

  if (!hotelId) {
    return undefined
  }

  return HOTEL_LIST_POOL.find((item) => item.itemId === hotelId) || HOTEL_LIST_POOL.find((item) => item.hotelId === hotelId)
}

export const getHotelDetailById = (hotelId?: string, listItemId?: string): HotelDetailData => {
  const listVariant = getListVariant(hotelId, listItemId)
  const baseHotelId = listVariant?.hotelId || hotelId
  const baseHotel = hotelCards.find((item) => item.id === baseHotelId) || hotelCards[0]
  const detailRecord = DETAIL_RECORDS[baseHotel.id]

  if (!detailRecord) {
    const fallbackDetail: HotelDetailData = {
      id: baseHotel.id,
      name: baseHotel.name,
      star: baseHotel.star,
      address: baseHotel.address,
      rating: 4.5,
      reviewCount: 2388,
      collectCount: 1568,
      facilities: [...baseHotel.tags],
      mapLabel: '热门商圈',
      gallery: [
        {
          id: 'g-fallback-1',
          title: '封面',
          imageUrl: baseHotel.coverImage,
        },
      ],
      roomPlans: [
        {
          id: `${baseHotel.id}-fallback`,
          name: '标准房',
          coverImage: baseHotel.coverImage,
          area: '30㎡',
          bedType: '1张大床',
          guestText: '2人',
          breakfast: '不含早餐',
          cancellable: true,
          tags: ['免费取消'],
          originalPrice: baseHotel.price + 200,
          price: baseHotel.price,
          stock: 5,
        },
      ],
    }

    if (!listVariant) {
      return fallbackDetail
    }

    return {
      ...fallbackDetail,
      name: listVariant.name,
      star: listVariant.star,
      address: listVariant.address,
      rating: listVariant.rating,
      reviewCount: listVariant.reviewCount,
      collectCount: listVariant.collectCount,
      mapLabel: `${listVariant.city.replace(/市$/, '')} · ${listVariant.locationZone}`,
      facilities: uniqueStrings([...fallbackDetail.facilities, ...listVariant.tags]),
    }
  }

  const baseDetail: HotelDetailData = {
    id: baseHotel.id,
    name: baseHotel.name,
    star: baseHotel.star,
    address: baseHotel.address,
    rating: detailRecord.rating,
    reviewCount: detailRecord.reviewCount,
    collectCount: detailRecord.collectCount,
    facilities: [...detailRecord.facilities],
    mapLabel: detailRecord.mapLabel,
    gallery: detailRecord.gallery.map((item) => ({ ...item })),
    roomPlans: cloneRoomPlans(detailRecord.roomPlans),
  }

  if (!listVariant) {
    return baseDetail
  }

  return {
    ...baseDetail,
    name: listVariant.name,
    star: listVariant.star,
    address: listVariant.address,
    rating: listVariant.rating,
    reviewCount: listVariant.reviewCount,
    collectCount: listVariant.collectCount,
    mapLabel: `${listVariant.city.replace(/市$/, '')} · ${listVariant.locationZone}`,
    facilities: uniqueStrings([...baseDetail.facilities, ...listVariant.tags]),
  }
}
